name: CI

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} 
    
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version

    - name: Run tests
      run: | 
        cargo test --verbose
    
    - name: Build
      run: | 
        cargo build --verbose